AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  DYNAMO_URL:
    Type: String
    Description: Dynamodb host url
  DYNAMO_REGION:
    Type: String
    Description: Dynamodb host url
    Default: local

Resources:

  BulkUpdateFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/handler
      Handler: bulk-update.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          DYNAMO_URL: !Ref DYNAMO_URL
          DYNAMO_REGION: !Ref DYNAMO_REGION
      Events:
        BulkUpdateLambdaApi:
          Type: Api
          Properties:
            Path: /bulk-update/{table}
            Method: put

  PatchLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/handler/
      Handler: patch.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          DYNAMO_URL: !Ref DYNAMO_URL
          DYNAMO_REGION: !Ref DYNAMO_REGION
      Events:
        PutLambdaApi:
          Type: Api
          Properties:
            Path: /{table}/{id}
            Method: put

