AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  BulkUpdateFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/handler
      Handler: bulk-update.handler
      Runtime: nodejs18.x
      Timeout: 10
      Events:
        BulkUpdateLambdaApi:
          Type: Api
          Properties:
            Path: /bulk-update/{table}
            Method: put

  PatchLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/handler/
      Handler: patch.handler
      Runtime: nodejs18.x
      Events:
        PutLambdaApi:
          Type: Api
          Properties:
            Path: /{table}/{id}
            Method: put

