AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  DYNAMO_URL:
    Type: String
    Description: Dynamodb host url
  DYNAMO_REGION:
    Type: String
    Description: Dynamodb host url
    Default: local

Resources:
  PutLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/handler/
      Handler: dbPut.handler
      Runtime: nodejs12.x 
              Environment:
          Variables:
            DYNAMO_URL: !Ref DYNAMO_URL
            DYNAMO_REGION: !Ref DYNAMO_REGION
      Events:
        PutLambdaApi:
          Type: Api
          Properties:
            Path: /{table}
            Method: put
  DeleteLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/handler/
      Handler: dbDelete.handler
      Runtime: nodejs12.x  
      Events:
        DeleteLambdaApi:
          Type: Api
          Properties:
            Path: /{table}/{id}
            Method: delete
Outputs:
  PostLambdaApi:
    Description: "API Gateway endpoint URL for GetLambdaFunction on dev stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"
  PostLambdaFunction:
    Description: "Post Lambda Function ARN"
    Value: !GetAtt PostLambdaFunction.Arn